### ISSUE TITLE
jcenter is deprecated

### ISSUE THREAD

**Issue by kaxonomy** [jagrosh/JagTag#10]
On February 1st, 2022, this dependency will no longer be able to resolve for new projects. Please migrate from jcenter to maven central.

**Comment by kaxonomy** [comment]
Library no longer resolves.

**Comment by duncte123** [comment]
Just use jitpack.io

**Comment by jagrosh** [comment]
JCenter will no longer be used for any new releases (which will use either jitpack or maven central), but JCenter for existing versions will continue to work "indefinitely."

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

Therefore, there is no need to switch away from JCenter until a new release is made.

---
> Library no longer resolves.

It does, you happened to attempt during an outage (https://stackoverflow.com/questions/70687342/jcenter-bintray-com-is-down-error-502-bad-gateway)
